version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"


services:
  identifier:
    image: semtech/mu-identifier:1.5.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
      - batch:batch
    volumes:
      - ./config/dispatcher:/config
    logging: *default-logging
  batch:
    image: lblod/batch-inzendingen-service
    logging: *default-logging
    links:
      - db:database
  file:
    image: semtech/mu-file-service:3.1.0
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    logging: *default-logging
    links:
      - db:database
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.17.1
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    logging: *default-logging
